# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170818_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecoveritem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
