# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20170817_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=20, verbose_name='专业')),
                ('message', models.TextField(verbose_name='消息')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布日期')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
